### ISSUE TITLE
怎么解析post请求的body呢？

### ISSUE THREAD

**Issue by LiuGangR** [XiaoMi/rose#3]
如题
只能读取输入流，自己解析？

**Comment by 54chen** [comment]
inv可以取出body，如果不是标准的键值对，需要自行解析。

**Comment by LiuGangR** [comment]
但是spring3.x，都支持requestBody注解了，rose可否支持呢

**Comment by 54chen** [comment]
暂时没有相关计划。

2014-11-13 15:16 GMT+08:00 LiuGangR notifications@github.com:

> 但是spring3.x，都支持requestBody注解了，rose可否支持呢
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/XiaoMi/rose/issues/3#issuecomment-62850916.

## 

## 

http://www.54chen.com
http://twitter.com/54chen

**Comment by bsqql123** [comment]
rose原生确实不支持，我自己用拦截器实现了一个类似于Spring 的@requestbody注解，可以接收application/json请求，可以作为轮子来使用，代码地址：
https://github.com/bsqql123/paoding-rose-hello/blob/master/src/main/java/net/paoding/rose/samples/hellorose/controllers/IndexController.java

拦截器实现在这里：
https://github.com/bsqql123/paoding-rose-hello/blob/master/src/main/java/net/paoding/rose/samples/hellorose/controllers/AccessTrackInterceptor.java
