### ISSUE TITLE
模糊查询应该怎么做啊

### ISSUE THREAD

**Issue by lfann** [XiaoMi/rose#8]
问个问题啊，DAO层的模糊查询应该如何做呢？ 貌似%不行啊

**Comment by wenjunli** [comment]
这个是sql的问题， 跟框架没啥关系

**Comment by lfann** [comment]
额额可能我没说明白 假如做模糊查询 在@SQL里应该怎么写呢？

**Comment by lfann** [comment]
弄好了，刚开始一直在@SQL的注解里写%%，后来改为在参数传到DAO层的时候就拼好%value%，没问题了。
